/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayFrame.java
 *
 * Created on Aug 16, 2010, 2:36:50 PM
 */

package pin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author mcgann
 */
public class DisplayFrame extends javax.swing.JFrame {

    final ImageFrame iframe;

    private Timer timer;

    private boolean moveOne = true;
    private boolean reverse = false;

    /** Creates new form DisplayFrame */
    public DisplayFrame(ImageFrame ifr) {
        this.iframe = ifr;
        initComponents();
        ((DisplayPanel)panel).setImageFrame(iframe);

        timer = new Timer(10, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if ( moveOne ) {
                    if ( !reverse ) {
                        iframe.forward();
                    } else {
                        iframe.backward();
                    }
                } else {
                    if ( !reverse ) {
                        iframe.forwardRow();
                    } else {
                        iframe.backwardRow();
                    }
                }
                updatePos();
            }
        });
        timer.setRepeats(true);
        updatePos();
    }

    private void updatePos() {
        textPos.setText(String.format("%x", iframe.position()));
        textHeight.setText(String.valueOf(iframe.getHeight()));
        textWidth.setText(String.valueOf(iframe.getWidth()));
        textDepth.setText(String.valueOf(iframe.getDepth()));
        checkMoveOne.setSelected(moveOne);
        checkReverse.setSelected(reverse);
        panel.repaint();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textPos = new javax.swing.JTextField();
        buttonNext = new javax.swing.JButton();
        buttonPrevious = new javax.swing.JButton();
        panel = new DisplayPanel();
        buttonGo = new javax.swing.JButton();
        buttonPlayStop = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        textWidth = new javax.swing.JTextField();
        textHeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textDepth = new javax.swing.JTextField();
        nextForwardOne = new javax.swing.JButton();
        buttonPreviousOne = new javax.swing.JButton();
        checkMoveOne = new javax.swing.JCheckBox();
        checkReverse = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Offset:");

        textPos.setText("jTextField1");

        buttonNext.setText(">>");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        buttonPrevious.setText("<<");
        buttonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPreviousActionPerformed(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        buttonGo.setText("Go");
        buttonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoActionPerformed(evt);
            }
        });

        buttonPlayStop.setText("Play");
        buttonPlayStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayStopActionPerformed(evt);
            }
        });

        jLabel2.setText("Dim:");

        textWidth.setText("jTextField1");

        textHeight.setText("jTextField1");

        jLabel3.setText("Depth:");

        textDepth.setText("jTextField1");

        nextForwardOne.setText(">");
        nextForwardOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextForwardOneActionPerformed(evt);
            }
        });

        buttonPreviousOne.setText("<");
        buttonPreviousOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPreviousOneActionPerformed(evt);
            }
        });

        checkMoveOne.setText("Move one");
        checkMoveOne.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkMoveOneStateChanged(evt);
            }
        });
        checkMoveOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMoveOneActionPerformed(evt);
            }
        });

        checkReverse.setText("Reverse");
        checkReverse.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkReverseStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textPos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(buttonGo))
                            .addComponent(checkReverse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonPlayStop, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkMoveOne))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonPreviousOne, 0, 0, Short.MAX_VALUE)
                            .addComponent(buttonPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nextForwardOne, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                            .addComponent(buttonNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNext)
                    .addComponent(buttonPrevious)
                    .addComponent(buttonPlayStop)
                    .addComponent(jLabel2)
                    .addComponent(textWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buttonGo)
                    .addComponent(textDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextForwardOne)
                    .addComponent(buttonPreviousOne)
                    .addComponent(checkMoveOne)
                    .addComponent(checkReverse))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        iframe.forwardRow();
        updatePos();
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPreviousActionPerformed
        iframe.backwardRow();
        updatePos();
    }//GEN-LAST:event_buttonPreviousActionPerformed

    private void buttonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoActionPerformed
       iframe.setPosition(Integer.parseInt(textPos.getText(), 16));
       iframe.setWidth(Integer.parseInt(textWidth.getText()));
       iframe.setHeight(Integer.parseInt(textHeight.getText()));
       iframe.setDepth(Integer.parseInt(textDepth.getText()));
       updatePos();
    }//GEN-LAST:event_buttonGoActionPerformed

    private void buttonPlayStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayStopActionPerformed
        if ( timer.isRunning() ) {
            timer.stop();
            buttonPlayStop.setText("Play");
        } else {
            timer.start();
            buttonPlayStop.setText("Stop");
        }

    }//GEN-LAST:event_buttonPlayStopActionPerformed

    private void nextForwardOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextForwardOneActionPerformed
        iframe.forward();
        updatePos();
    }//GEN-LAST:event_nextForwardOneActionPerformed

    private void buttonPreviousOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPreviousOneActionPerformed
        iframe.backward();
        updatePos();
    }//GEN-LAST:event_buttonPreviousOneActionPerformed

    private void checkMoveOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMoveOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMoveOneActionPerformed

    private void checkMoveOneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkMoveOneStateChanged
        this.moveOne = checkMoveOne.isSelected();
        updatePos();
    }//GEN-LAST:event_checkMoveOneStateChanged

    private void checkReverseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkReverseStateChanged
        this.reverse = checkReverse.isSelected();
    }//GEN-LAST:event_checkReverseStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGo;
    private javax.swing.JButton buttonNext;
    private javax.swing.JToggleButton buttonPlayStop;
    private javax.swing.JButton buttonPrevious;
    private javax.swing.JButton buttonPreviousOne;
    private javax.swing.JCheckBox checkMoveOne;
    private javax.swing.JCheckBox checkReverse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton nextForwardOne;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField textDepth;
    private javax.swing.JTextField textHeight;
    private javax.swing.JTextField textPos;
    private javax.swing.JTextField textWidth;
    // End of variables declaration//GEN-END:variables

}
